name: Publish
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: login
        run: |
          echo "@archimedes:registry=http://registry.npmjs.org/" >> .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - name: publish
        run: "npm run lerna publish --yes --canary --message 'chore: release new versions'"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
